version: '3'
services:
  docker-api-server:
    build:
      context: .
      dockerfile: dockerApiServerDockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../docker-api-server-nodejs:/code
    networks:
      - inside-node-bridge
  docker-api-client:
    build:
      context: .
      dockerfile: dockerApiClientDockerfile
    networks:
      - inside-node-bridge
    volumes:
      - ../trust-engine:/code
    depends_on:
      - docker-api-server
networks:
  inside-node-bridge:
    driver: bridge
  connect-host:
    driver: host  
